language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a

before_install:
  - wget https://services.gradle.org/distributions/gradle-2.4-bin.zip
  - unzip gradle-2.4-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.4
  - export PATH=$GRADLE_HOME/bin:$PATH
  - echo yes | android update sdk --filter sysimg-22 --no-ui --force > /dev/null

branches:
  only:
    - build

android:
  components:
    - build-tools-22.0.1
    - android-22
    - platform-tools
    - extra-android-support
    - extra-android-m2repository
    - 

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &
script:
  - gradle connectedAndroidTest